apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: aws:iam::246491821862:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::246491821862:role/eksctl-eksctl-demo-nodegroup-ng-5-NodeInstanceRole-1CBS1C8AZCKQE
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T21:24:24Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "97409"
  uid: 7faa2314-1bdc-41e6-bfb9-94c43cdb9105
